apiVersion: v1
kind: PersistentVolume
metadata:
  name: libraryapp-sqlite-pv
spec:
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/k8s/libraryapp/sqlite"
    type: DirectoryOrCreate